
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-5
pull_requests: [{"author":{"id":"MDQ6VXNlcjM4MzkzMjM5","is_bot":false,"login":"tejasvissa813","name":""},"headRefName":"TV-MenuItemReview-form","number":89,"title":"MenuItemReview Form Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/89"},{"author":{"id":"MDQ6VXNlcjYxMzYwOTU1","is_bot":false,"login":"rileychou","name":"Riley Chou"},"headRefName":"rc-UCSBDiningCommonsMenuItem-placeholder","number":88,"title":"copy placeholders to navbar","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/88"},{"author":{"id":"U_kgDOBXm5-g","is_bot":false,"login":"walexgreen","name":"William Greenwald"},"headRefName":"WG-HelpRequest-Component","number":87,"title":"WG - HelpRequest: Completed Form Component items for issue #46","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/87"}]
