
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-5
pull_requests: [{"author":{"id":"U_kgDOBXm5-g","is_bot":false,"login":"walexgreen","name":"William Greenwald"},"headRefName":"WG-HelpRequest-h05","number":125,"title":"Wg help request h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/125"},{"author":{"id":"U_kgDOBdlAFQ","is_bot":false,"login":"maidang111","name":""},"headRefName":"MD-HW05","number":124,"title":"Added RecommendationRequestIT and RecommendationRequestWebIT","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/124"},{"author":{"id":"MDQ6VXNlcjYxMzYwOTU1","is_bot":false,"login":"rileychou","name":"Riley Chou"},"headRefName":"rc-UCSBDiningCommonsMenuItems-integration","number":123,"title":"Ucsb dining commons menu items integration","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/123"}]
