
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-5
pull_requests: [{"author":{"id":"U_kgDOBXm5-g","is_bot":false,"login":"walexgreen","name":"William Greenwald"},"headRefName":"WG-HelpRequest-Edit","number":107,"title":"wg - HelpRequest Edit","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/107"},{"author":{"id":"MDQ6VXNlcjYxMzYwOTU1","is_bot":false,"login":"rileychou","name":"Riley Chou"},"headRefName":"rc-UCSBDiningCommonsMenuItem-index","number":106,"title":"UCSB Dining Commons Menu Items Index page","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/106"},{"author":{"id":"MDQ6VXNlcjM2MTM3NjU0","is_bot":false,"login":"Ononymous","name":"Gen Tamada"},"headRefName":"GT-UCSBOrganization-h05","number":105,"title":"UCSB Organization Integration test h05","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/105"},{"author":{"id":"U_kgDOBdlAFQ","is_bot":false,"login":"maidang111","name":""},"headRefName":"MD-RecommendationRequest-pagesEdit","number":103,"title":"Added RecommendationRequest Edit Pages ","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-5/pull/103"}]
